### ISSUE TITLE
Choppiness & huge audio delay over USB tethering

### ISSUE THREAD

**Issue by LoganDark** [teamclouday/AndroidMic#2]
Here's what my voice sounds like over Discord using AndroidMic:

https://cdn.discordapp.com/attachments/252112570423443456/960636721073098822/Record_2022-04-04_at_13h26m54s.wav

there's also an audio delay of around 2 seconds.

AndroidMic.exe process priority is set to real-time

**Comment by teamclouday** [comment]
Thanks for trying the app! Had similar experience about the sound quality and dely. I'm not actively working on this project, but will definitely take a look into it later.

**Comment by LoganDark** [comment]
@teamclouday I decided to just bite the bullet and get a $10 microphone from Amazon. My laptop's audio system is fried but I was able to get around it by using a USB-C-to-3.5mm adapter. So, no need for this solution anymore :)

But glad to hear that you were able to solve the issue! Closing.
