### ISSUE TITLE
Use rnnoise

### ISSUE THREAD

**Issue by wiiznokes** [teamclouday/AndroidMic#20]
Use [rnnoise](https://github.com/xiph/rnnoise) for better noise suppression

**Comment by teamclouday** [comment]
Thanks for sharing! I'll take a look later.\
Btw, if you happen to know any open-source real-time solution for echo cancellation, please let me know!

**Comment by wiiznokes** [comment]
You're welcome, I just found it while recording with OBS Studio and it's really amazing.
And the current echo/noise cancellation and VAD seems a bit buggy to me, like I'm under a tunnel.
I tried to compile without success on Windows, to complex for me. I also found [this](https://github.com/Neos-Metaverse/RNNoise.NET), apparently a Wrapper for C#.


>Btw, if you happen to know any open-source real-time solution for echo cancellation, please let me know!

OK, no problem!

**Comment by teamclouday** [comment]
Yeah, I agree it's a little buggy. And there're too few samples online for `speexdsp` so honestly I'm not sure my implementation and configurations are 100% correct.

For `rnnoise`, as long as I can compile the dll for it, I can write C# wrapper easily, so that's not too much to worry about🙂

**Comment by teamclouday** [comment]
Hey, the `rnnoise` is merged to main branch. Please have a try! 👍

**Comment by wiiznokes** [comment]
Hey, I've tested it and it work great! Good job!👍
