### ISSUE TITLE
Usb request

### ISSUE THREAD

**Issue by wiiznokes** [teamclouday/AndroidMic#5]
Hi,
thanks you for this great app.
I wanted to use my android mic to cummunicate (discord, games, ...).
I'm a beginer in programmation and I would like to try to do that,
Also, I can't use wifi, so I think I will begin to try implement usb for passing data.
So, if you have any lead to how accualy do that, it would be my pleasure.
Thanks

**Comment by teamclouday** [comment]
So for usb connection, there are two ways I can think of:  
1. Use [adb](https://developer.android.com/studio/command-line/adb) to forward data to phone.  
    I had a working prototype in [dev-usb-adb](https://github.com/teamclouday/AndroidMic/tree/dev-usb-adb) branch. It requires enabling usb debugging in Android developer setting. Besides that, it is a server/client TCP connection. The code there is too old, in abandoned state.  
2.  Use [usb tethering](https://www.geeksforgeeks.org/what-is-usb-tethering-and-how-to-enable-it/).  
     It essentially let PC access your phone's network. You can set [network priority](https://www.windowscentral.com/how-change-priority-order-network-adapters-windows-10) in Windows so that your PC does not use up all the bandwidth, especially when on mobile data. Again the rest is just TCP connection as usual. I think the current release works with usb tethering, though I haven't fully tested it. You can try to select the Wifi option but set up connection with usb tethering and see if it works.

**Comment by wiiznokes** [comment]
Ok, I will try with usb tethering.
Thank you for the information.
